/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    resources: Resource;
    bookmarks: Bookmark;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'editor' | 'user')[] | null;
  firstName?: string | null;
  lastName?: string | null;
  bio?: string | null;
  phoneNumber?: string | null;
  social_links?:
    | {
        platform?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  type: 'academic' | 'case_study' | 'evaluation' | 'framework' | 'multimedia' | 'policy' | 'report' | 'toolkit';
  good_practice: 'yes' | 'no';
  /**
   * Select up to 3 themes
   */
  themes?:
    | (
        | 'Industrial, technical and vocational training'
        | 'Gender and Transformation'
        | 'Entrepreneurship and informal sector formalisation'
        | 'Human Capital Development'
        | 'Agribusiness and agricultural skills'
        | 'Labour migration & mobility'
        | 'Digital skills & future of work'
        | 'Education systems & policy'
        | 'Financing & investment in skills'
        | 'Informal sector & livelihoods'
        | 'Green skills / sustainability'
        | 'Innovation & partnerships'
        | 'Governance'
      )[]
    | null;
  /**
   * Select up to 3 target groups
   */
  target_groups?:
    | (
        | 'Policymakers'
        | 'Educators & Implementers'
        | 'Youth'
        | 'Private Sector / Employers'
        | 'Researchers'
        | 'TVET Managers / Principals'
        | 'HR / Labour Market Actors'
        | 'Donors & Development Partners'
      )[]
    | null;
  language: 'English' | 'French' | 'Portuguese' | 'Arabic' | 'Other';
  /**
   * Select one or more countries this resource applies to
   */
  countries?:
    | (
        | 'Algeria'
        | 'Egypt'
        | 'Libya'
        | 'Morocco'
        | 'Sudan'
        | 'Tunisia'
        | 'Benin'
        | 'Burkina_Faso'
        | 'Cape_Verde'
        | 'Cote_dIvoire'
        | 'Gambia'
        | 'Ghana'
        | 'Guinea'
        | 'Guinea_Bissau'
        | 'Liberia'
        | 'Mali'
        | 'Mauritania'
        | 'Niger'
        | 'Nigeria'
        | 'Senegal'
        | 'Sierra_Leone'
        | 'Togo'
        | 'Cameroon'
        | 'Central_African_Republic'
        | 'Chad'
        | 'Democratic_Republic_of_Congo'
        | 'Equatorial_Guinea'
        | 'Gabon'
        | 'Republic_of_Congo'
        | 'Sao_Tome_and_Principe'
        | 'Burundi'
        | 'Comoros'
        | 'Djibouti'
        | 'Eritrea'
        | 'Ethiopia'
        | 'Kenya'
        | 'Madagascar'
        | 'Mauritius'
        | 'Rwanda'
        | 'Seychelles'
        | 'Somalia'
        | 'South_Sudan'
        | 'Tanzania'
        | 'Uganda'
        | 'Angola'
        | 'Botswana'
        | 'Eswatini'
        | 'Lesotho'
        | 'Malawi'
        | 'Mozambique'
        | 'Namibia'
        | 'South_Africa'
        | 'Zambia'
        | 'Zimbabwe'
      )[]
    | null;
  /**
   * Select the regional scope this resource applies to
   */
  region?:
    | ('Continental' | 'East_Africa' | 'West_Africa' | 'Central_Africa' | 'North_Africa' | 'Southern_Africa')
    | null;
  /**
   * Enter the year the resource was published
   */
  year_published?: number | null;
  /**
   * Select a publisher or choose "Other" to enter a custom publisher
   */
  publisher?:
    | (
        | 'African Union'
        | 'ILO'
        | 'AUDA-NEPAD'
        | 'UNESCO'
        | 'World Bank'
        | 'African Development Bank'
        | 'UNECA'
        | 'UNICEF'
        | 'UNDP'
        | 'GIZ'
        | 'British Council'
        | 'European Union'
        | 'USAID'
        | 'Other'
      )
    | null;
  /**
   * Enter custom publisher name (only if "Other" is selected above)
   */
  custom_publisher?: string | null;
  /**
   * Upload a featured image for this resource
   */
  featured_image?: (number | null) | Media;
  description: string;
  link: string;
  /**
   * Upload files related to this resource
   */
  files: {
    file: number | Media;
    /**
     * Enter a description for this file
     */
    description?: string | null;
    id?: string | null;
  }[];
  /**
   * Upload additional files related to this resource
   */
  additional_files?:
    | {
        file: number | Media;
        /**
         * Enter a description for this file
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User favourites for quick access to resources
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: number;
  user: number | User;
  resource: number | Resource;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: number | Bookmark;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  firstName?: T;
  lastName?: T;
  bio?: T;
  phoneNumber?: T;
  social_links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  good_practice?: T;
  themes?: T;
  target_groups?: T;
  language?: T;
  countries?: T;
  region?: T;
  year_published?: T;
  publisher?: T;
  custom_publisher?: T;
  featured_image?: T;
  description?: T;
  link?: T;
  files?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  additional_files?:
    | T
    | {
        file?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  user?: T;
  resource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}